### ISSUE TITLE
Bad dependencies in package.json

### ISSUE THREAD

**Issue by polskataga** [ALXRSS/WebRTC-Conf#19]
The dependencies' version in package.json generate a folder node_modules not compatible with the project.

**Comment by micbuffa** [comment]
Just remove the tildes and + before the versions of the modules in package.json. This will "force" the versions of the modules and it will work. One package has been updated  and it breaks compatibility with others. If you have time, just try to remove the tildes and + one by one in order to identify the module that causes the error.

**Comment by polskataga** [comment]
Yes, we justly have tried this but we have to remove the tildes also in the several submodules called by the modules. We are thinking about a lockdown.json file to lock the version of the modules.

We are working on it. Thank you for your help.

**Comment by micbuffa** [comment]
I had the same problem. Just rename node_modules. Then edit package.json, let only the fixed versions. Redo npm install and it should work. Do a shift-reload too.

**Comment by polskataga** [comment]
It seems to work like this.
