### ISSUE TITLE
visio1.gexsoft.com = many2many-current online + errors

### ISSUE THREAD

**Issue by micbuffa** [ALXRSS/WebRTC-Conf#44]
Hello, I put online the many2many-current branch, available at visio1.gexsoftcom

Can you test it, check that everything is ok, etc. I've found strange errors in the console :+1: 
<a href="http://imgur.com/jGc75fp"><img src="http://i.imgur.com/jGc75fp.jpg" title="Hosted by imgur.com" /></a>

**Comment by Desiderius77** [comment]
At my turn to have a stange behavior !

When i call visio1.gexsoft.com, I get
the usual background and headers but nothing else : no login popup !
( Firefox Linux )

**Comment by micbuffa** [comment]
Yes, look at the errors in the console !!!!! Tell me what to do.

**Comment by micbuffa** [comment]
Be sure to test a "fresh install" in a new dir, and please provide a "good" package.json file. Then, when it works for you on a fresh install, push it and tell me when I update the online version.

**Comment by micbuffa** [comment]
And be sure to propagate the bug fixes from one version to the others... like the socket.io.connect call that must have NO parameter etc.

**Comment by polskataga** [comment]
The socket.io.connect() call has no more parameters.

**Comment by polskataga** [comment]
Despite of that many2many-curent-version works now, this version is not updated with the latest features as one2many-current-version.

In this fact, perhaps we have to delete the many2many version from WebRTC-Conf since we are focused on one2many. Besides many2many is already in https://github.com/ALXRSS/WebRTC

So you can put the cleanest version :  many2many-stable-version and even better from https://github.com/ALXRSS/WebRTC/tree/master/Prototype/current%20version

**Comment by micbuffa** [comment]
Tell me if I need to update the online versions. I would recommend to have a real functional n x n version, as a 1 - 1 version is way too limited to have an impact.
